version: '3'

services:
  web:
    build: .
    volumes:
      - static_vol:/app/static
      - media_vol:/app/media
    ports:
      - "8000:8000"
  nginx:
    build: ./nginx
    volumes:
      - static_vol:/app/static
      - media_vol:/app/media
    ports:
      -  "80:80"
    depends_on:
      - web

volumes:
  static_vol:
  media_vol: